## FIRST LINE/ROW: Info & Status
# First param â”€â”Œ
[username]
format = "[$user]($style)@"
style_user = "bold #0087AF"
style_root = "bold #0087AF"
show_always = true

# Second param
[hostname]
format = "[$hostname]($style) "
style = "bold #0087AF"
trim_at = "-"
ssh_only = false
disabled = false


# Prompt: param 2 â””â”€
[character]
success_symbol = "[â¯](bold #5FD700)"
error_symbol = "(bold red)"

# Third param
[directory]
style = "#00AFFF"
truncation_length = 8
truncate_to_repo = false
truncation_symbol = 'â€¦/'

[directory.substitutions]
"Documents" = "ïœ˜ "
"Downloads" = "ï€™ "
"Music" = "ï€ "
"Pictures" = "ï€¾ "

[status]
style = "bold white"
format = '[\[$symbol$status_common_meaning$status_signal_name$status_maybe_int\]]($style)'
map_symbol = true
disabled = false

[aws]
style = "#edd2ab"
symbol = "îŒ½ Â "

[buf]
style = "#edd2ab"
symbol = "ï’ "

[c]
style = "#edd2ab"
symbol = "î˜ "

[conda]
style = "#edd2ab"
symbol = "ï„Œ "

[dart]
style = "#edd2ab"
symbol = "î˜ "

[docker_context]
symbol = "ïŒˆ "
detect_files = ["docker-compose.yml", "docker-compose.yaml", "Dockerfile"]
format = "via [$symbol$context]($style) "
style = "#edd2ab"
only_with_files = true
disabled = false

[elixir]
style = "#edd2ab"
symbol = "î‰µ "

[elm]
style = "#edd2ab"
symbol = "î˜¬ "

[fossil_branch]
style = "#edd2ab"
symbol = "ï˜ "

[git_branch]
symbol = "ï˜ "
style = "#5FAF00"

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
style = "#5FAF00"

[git_status]
style = "#5FAF00"

[golang]
style = "#edd2ab"
symbol = "î˜§ "

[guix_shell]
style = "#edd2ab"
symbol = "ïŒ¥ "

[haskell]
style = "#edd2ab"
symbol = "î· "

[haxe]
style = "#edd2ab"
symbol = "âŒ˜ "

[hg_branch]
style = "#edd2ab"
symbol = "ï˜ "

[java]
style = "#edd2ab"
symbol = "î‰– "

[julia]
style = "#edd2ab"
symbol = "î˜¤ "

[lua]
style = "#edd2ab"
symbol = "î˜  "

[memory_usage]
style = "#edd2ab"
symbol = "ó°› "

[meson]
style = "#edd2ab"
symbol = "ó°”· "

[nim]
style = "#edd2ab"
symbol = "ó°†¥ "

[nix_shell]
style = "#edd2ab"
symbol = "ïŒ“ "

[nodejs]
style = "#edd2ab"
symbol = "îœ˜ "

[os.symbols]
Alpaquita = "îª¢ "
Alpine = "ïŒ€ "
Amazon = "ï‰° "
Android = "ï…» "
Arch = "ïŒƒ "
Artix = "ïŒŸ "
CentOS = "ïŒ„ "
Debian = "ïŒ† "
DragonFly = "îŠ "
Emscripten = "ïˆ… "
EndeavourOS = "ï†— "
Fedora = "ïŒŠ "
FreeBSD = "ïŒŒ "
Garuda = "ó°›“ "
Gentoo = "ïŒ "
HardenedBSD = "ó°Œ "
Illumos = "ó°ˆ¸ "
Linux = "ïŒš "
Mabox = "î¬© "
Macos = "ïŒ‚ "
Manjaro = "ïŒ’ "
Mariner = "ï‡ "
MidnightBSD = "ï†† "
Mint = "ïŒ "
NetBSD = "ï€¤ "
NixOS = "ïŒ“ "
OpenBSD = "ó°ˆº "
openSUSE = "ïŒ” "
OracleLinux = "ó°Œ· "
Pop = "ïŒª "
Raspbian = "ïŒ• "
Redhat = "ïŒ– "
RedHatEnterprise = "ïŒ– "
Redox = "ó°€˜ "
Solus = "ó° ³ "
SUSE = "ïŒ” "
Ubuntu = "ïŒ› "
Unknown = "ïˆ­ "
Windows = "ó°² "

[package]
style = "#edd2ab"
symbol = 'ğŸ“¦ '

[pijul_channel]
style = "#edd2ab"
symbol = " "

[python]
style = "#edd2ab"
symbol = "îˆµ "

[rlang]
style = "#edd2ab"
symbol = "ó°Ÿ” "

[ruby]
style = "#edd2ab"
symbol = "î‘ "

[rust]
style = "#edd2ab"
symbol = "î¨ "

[scala]
style = "#edd2ab"
symbol = "îœ· "

[spack]
style = "#edd2ab"
symbol = "ğŸ…¢ "